version: '3'

services:
    rails:
        build : 
            context: ./Dockerfiles
        image: joaovfg/rubycontainer:1.1
        volumes:
            - "C:/Users/jintahibari/Documents/DOCKER:/projects"
        ports:
            - "3000"
            - "22" 
    
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - basedados:/var/lib/postgresql/data
        ports:
            - "5432"
#Necessario criar o volume de maneira externa : docker volume create basedados
volumes:
  basedados:
    external: true