version: '3'

services:
    rails:
        build : 
            context: ./Dockerfiles
        image: joaovfg/rubycontainer:1.1
        volumes:
            - "C:/Users/jintahibari/Documents/DOCKER:/projects"
        ports:
            - "3000"
            - "22" 
      